version: 2.1
orbs:
  node: circleci/node@4.2.0
workflows:
  test-and-deploy:
    jobs:
      - do-testing
      - build-and-deploy:
          requires:
            - do-testing
jobs:
  do-testing:
    docker:
      - image: 'cimg/node:15.11.0-browsers'
    steps:
      - checkout
      - run: "npm get registry"
      - node/install-packages
      - run: "npm run test:unit"
#      - run: "npm run test:e2e-headless"
  build-and-deploy:
    executor: node/default
    steps:
      - checkout
      - node/install-packages
      - run:
          name: Build
          command: npm run build
      - run:
          name: Deploy Netlify
          command: npx netlify deploy --prod --dir=dist