version: 2.1
orbs:
  node: circleci/node@4.2.0
workflows:
  test-and-deploy:
    jobs:
      - tests
      - build-and-deploy:
          requires:
            - tests

jobs:
  tests:
    executor:
      name: node/default
      tag: '14.16'
    steps:
      - checkout
      - node/install
      - run:
          name: UnitTest
          command: npm run test:unit
      - run:
          name: E2e
          command: npm run test:e2e
  build-and-deploy:
    executor: node/default
    steps:
      - checkout
      - node/install-packages
      - run:
          name: Build
          command: npm run build
      - run:
          name: Deploy Netlify
          command: npx netlify deploy --prod --dir=dist